### ISSUE TITLE
Figure out world regions for reporting indicator

### ISSUE THREAD

**Issue by ColinKhoury** [CIAT-DAPA/aichi13#97]
We should report the indicator at global, country, and regional levels
For Regional- we need to figure out what the normal regional classifications the CBD uses and use that to classify the countries (i.e. the isos in the file with all the species and all the isos) into regions so that we can run the indicator steps not only for countries but also for these regions. Not necessary for preliminary report but needed for final output.

**Comment by danipilze** [comment]
done for UN regions
